=== onecodex/onecodex/tests/api_data/schema_jobs.json
{"$schema": "http://json-schema.org/draft-04/hyper-schema#", "links": [{"href": "/api/v1/jobs/schema", "method": "GET", "rel": "describedBy"}, {"href": "/api/v1/jobs", "method": "GET", "rel": "instances", "schema": {"additionalProperties": true, "properties": {"page": {"default": 1, "minimum": 1, "type": "integer"}, "per_page": {"default": 20, "maximum": 1000, "minimum": 1, "type": "integer"}, "sort": {"additionalProperties": false, "properties": {"$uri": {"description": "Sort by $uri in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "analysis_type": {"description": "Sort by analysis_type in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "created_at": {"description": "Sort by created_at in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "name": {"description": "Sort by name in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "public": {"description": "Sort by public in descending order if 'true', ascending order if 'false'.", "type": "boolean"}}, "type": "object"}, "where": {"additionalProperties": false, "properties": {"$uri": {"anyOf": [{"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}, {"additionalProperties": false, "properties": {"$eq": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}, "analysis_type": {"anyOf": [{"additionalProperties": false, "properties": {"$startswith": {"minLength": 1, "type": "string"}}, "required": ["$startswith"], "type": "object"}, {"maxLength": 50, "type": ["string", "null"]}, {"additionalProperties": false, "properties": {"$contains": {"minLength": 1, "type": "string"}}, "required": ["$contains"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"maxLength": 50, "type": ["string", "null"]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$iendswith": {"minLength": 1, "type": "string"}}, "required": ["$iendswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$icontains": {"minLength": 1, "type": "string"}}, "required": ["$icontains"], "type": "object"}, {"additionalProperties": false, "properties": {"$endswith": {"minLength": 1, "type": "string"}}, "required": ["$endswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$istartswith": {"minLength": 1, "type": "string"}}, "required": ["$istartswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"maxLength": 50, "type": ["string", "null"]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}, {"additionalProperties": false, "properties": {"$eq": {"maxLength": 50, "type": ["string", "null"]}}, "required": ["$eq"], "type": "object"}]}, "created_at": {"anyOf": [{"additionalProperties": false, "properties": {"$gt": {"format": "date-time", "type": "string"}}, "required": ["$gt"], "type": "object"}, {"additionalProperties": false, "properties": {"$gte": {"format": "date-time", "type": "string"}}, "required": ["$gte"], "type": "object"}, {"format": "date-time", "type": "string"}, {"additionalProperties": false, "properties": {"$ne": {"format": "date-time", "type": "string"}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$lt": {"format": "date-time", "type": "string"}}, "required": ["$lt"], "type": "object"}, {"additionalProperties": false, "properties": {"$lte": {"format": "date-time", "type": "string"}}, "required": ["$lte"], "type": "object"}, {"additionalProperties": false, "properties": {"$between": {"default": [], "items": {"format": "date-time", "type": "string"}, "maxItems": 2, "minItems": 2, "type": "array"}}, "required": ["$between"], "type": "object"}, {"additionalProperties": false, "properties": {"$eq": {"format": "date-time", "type": "string"}}, "required": ["$eq"], "type": "object"}]}, "name": {"anyOf": [{"additionalProperties": false, "properties": {"$startswith": {"minLength": 1, "type": "string"}}, "required": ["$startswith"], "type": "object"}, {"maxLength": 60, "type": ["string", "null"]}, {"additionalProperties": false, "properties": {"$contains": {"minLength": 1, "type": "string"}}, "required": ["$contains"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"maxLength": 60, "type": ["string", "null"]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$iendswith": {"minLength": 1, "type": "string"}}, "required": ["$iendswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$icontains": {"minLength": 1, "type": "string"}}, "required": ["$icontains"], "type": "object"}, {"additionalProperties": false, "properties": {"$endswith": {"minLength": 1, "type": "string"}}, "required": ["$endswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$istartswith": {"minLength": 1, "type": "string"}}, "required": ["$istartswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"maxLength": 60, "type": ["string", "null"]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}, {"additionalProperties": false, "properties": {"$eq": {"maxLength": 60, "type": ["string", "null"]}}, "required": ["$eq"], "type": "object"}]}, "public": {"anyOf": [{"default": false, "type": ["boolean", "null"]}, {"additionalProperties": false, "properties": {"$eq": {"default": false, "type": ["boolean", "null"]}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"default": false, "type": ["boolean", "null"]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"default": false, "type": ["boolean", "null"]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}}, "type": "object"}}, "type": "object"}, "targetSchema": {"items": {"$ref": "#"}, "type": "array"}}, {"href": "/api/v1/jobs/{id}/run", "method": "POST", "rel": "run", "schema": {"additionalProperties": false, "properties": {"force": {"default": false, "type": "boolean"}, "job_args": {"additionalProperties": {"type": ["null", "string", "number", "boolean", "object", "array"]}, "type": "object"}, "sample": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}}, "required": ["sample", "job_args"], "type": "object"}, "targetSchema": {"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/analyses\\/[^/]+$", "type": "string"}}, "type": "object"}}, {"href": "/api/v1/jobs/{id}", "method": "GET", "rel": "self", "targetSchema": {"$ref": "#"}}], "properties": {"$uri": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "readOnly": true, "type": "string"}, "analysis_type": {"maxLength": 50, "type": ["string", "null"]}, "created_at": {"format": "date-time", "readOnly": true, "type": "string"}, "name": {"maxLength": 60, "type": ["string", "null"]}, "public": {"default": false, "type": ["boolean", "null"]}}, "type": "object"}

=== onecodex/onecodex/tests/api_data/jobs.json
[{"$uri": "/api/v1/jobs/47c4fe23588640a9", "analysis_type": "typing", "created_at": "2015-04-28T17:45:49-07:00", "name": "One Codex S. enterica Typing", "public": false}, {"$uri": "/api/v1/jobs/1ede4125214542e0", "analysis_type": "classification", "created_at": "2015-08-31T16:38:25.833478-07:00", "name": "One Codex 38K Database", "public": false}, {"$uri": "/api/v1/jobs/e4b1ab37ff554c53", "analysis_type": "classification", "created_at": "2015-09-01T10:11:15.493388-07:00", "name": "RefSeq Complete Genomes", "public": true}, {"$uri": "/api/v1/jobs/c4f763556452402c", "analysis_type": "panel", "created_at": "2015-09-11T17:43:58.818569-07:00", "name": "ARD Panel v1", "public": false}, {"$uri": "/api/v1/jobs/9359554ff4f34137", "analysis_type": "alignment", "created_at": "2015-09-14T13:20:15.528558-07:00", "name": "Alignment Run", "public": false}, {"$uri": "/api/v1/jobs/d512cb556241440f", "analysis_type": "classification", "created_at": "2015-11-01T16:27:19.140577-08:00", "name": "One Codex Database", "public": true}, {"$uri": "/api/v1/jobs/52c73e0c9a4d4b3f", "analysis_type": "classification", "created_at": "2015-11-01T16:28:03.974596-08:00", "name": "RefSeq Complete Genomes", "public": true}, {"$uri": "/api/v1/jobs/b18ea5e828224e3c", "analysis_type": "classification", "created_at": "2016-02-08T13:56:55.156056-08:00", "name": "One Codex Database w/NNLS", "public": true}, {"$uri": "/api/v1/jobs/0d558feada6f47ac", "analysis_type": "classification", "created_at": "2016-02-09T08:38:49.504357-08:00", "name": "One Codex Database w/NNLS", "public": true}, {"$uri": "/api/v1/jobs/c3caae64b63b4f07", "analysis_type": "classification", "created_at": "2016-04-07T14:47:36.054255-07:00", "name": "One Codex", "public": false}, {"$uri": "/api/v1/jobs/7076363bfd204971", "analysis_type": "classification", "created_at": "2016-05-01T17:28:52.104426-07:00", "name": "Targeted Loci Database", "public": true}, {"$uri": "/api/v1/jobs/dfe7c6eaffb1408f", "analysis_type": "control", "created_at": "2017-04-28T15:27:40.140791-07:00", "name": "MSA-1000", "public": true}, {"$uri": "/api/v1/jobs/4c042ebc86234fcf", "analysis_type": "control", "created_at": "2017-04-28T15:28:37.854161-07:00", "name": "MSA-1001", "public": true}, {"$uri": "/api/v1/jobs/179922c5e2354350", "analysis_type": "control", "created_at": "2017-04-28T15:29:11.689322-07:00", "name": "MSA-1002", "public": true}, {"$uri": "/api/v1/jobs/528ba0c040c441d1", "analysis_type": "control", "created_at": "2017-04-28T15:29:34.891680-07:00", "name": "MSA-1003", "public": true}, {"$uri": "/api/v1/jobs/8cffba5f663b43ee", "analysis_type": "control", "created_at": "2017-04-28T15:30:03.659835-07:00", "name": "MSA-2002", "public": true}, {"$uri": "/api/v1/jobs/3738a405bce3433e", "analysis_type": "control", "created_at": "2017-04-28T15:30:38.538526-07:00", "name": "MSA-2003", "public": true}, {"$uri": "/api/v1/jobs/fcb56913874c455b", "analysis_type": "control", "created_at": "2017-04-28T15:29:11.689322-07:00", "name": "MSA-1002", "public": true}, {"$uri": "/api/v1/jobs/ce53e9546fcd46d2", "analysis_type": "control", "created_at": "2017-04-28T15:29:34.891680-07:00", "name": "MSA-1003", "public": true}, {"$uri": "/api/v1/jobs/7252502523f44966", "analysis_type": "control", "created_at": "2017-04-28T15:30:03.659835-07:00", "name": "MSA-2002", "public": true}, {"$uri": "/api/v1/jobs/1605813a0e574add", "analysis_type": "control", "created_at": "2017-04-28T15:30:38.538526-07:00", "name": "MSA-2003", "public": true}, {"$uri": "/api/v1/jobs/d7ddbb374b2a4d75", "analysis_type": "control", "created_at": "2017-04-28T15:27:40.140791-07:00", "name": "MSA-1000", "public": true}, {"$uri": "/api/v1/jobs/08e251c5dfb5405f", "analysis_type": "control", "created_at": "2017-04-28T15:28:37.854161-07:00", "name": "MSA-1001", "public": true}]
