=== onecodex/onecodex/tests/api_data/schema_classifications.json
{"$schema": "http://json-schema.org/draft-04/hyper-schema#", "links": [{"href": "/api/v1/classifications/schema", "method": "GET", "rel": "describedBy"}, {"href": "/api/v1/classifications/{id}/files", "method": "GET", "rel": "files", "targetSchema": {"type": "string"}}, {"href": "/api/v1/classifications", "method": "GET", "rel": "instances", "schema": {"additionalProperties": true, "properties": {"page": {"default": 1, "minimum": 1, "type": "integer"}, "per_page": {"default": 20, "maximum": 1000, "minimum": 1, "type": "integer"}, "sort": {"additionalProperties": false, "properties": {"$uri": {"description": "Sort by $uri in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "complete": {"description": "Sort by complete in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "created_at": {"description": "Sort by created_at in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "error_msg": {"description": "Sort by error_msg in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "job": {"description": "Sort by job in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "sample": {"description": "Sort by sample in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "success": {"description": "Sort by success in descending order if 'true', ascending order if 'false'.", "type": "boolean"}}, "type": "object"}, "where": {"additionalProperties": false, "properties": {"$uri": {"anyOf": [{"pattern": "^\\/api\\/v1\\/classifications\\/[^/]+$", "type": "string"}, {"additionalProperties": false, "properties": {"$eq": {"pattern": "^\\/api\\/v1\\/classifications\\/[^/]+$", "type": "string"}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"pattern": "^\\/api\\/v1\\/classifications\\/[^/]+$", "type": "string"}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"pattern": "^\\/api\\/v1\\/classifications\\/[^/]+$", "type": "string"}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}, "complete": {"anyOf": [{"type": ["boolean", "null"]}, {"additionalProperties": false, "properties": {"$eq": {"type": ["boolean", "null"]}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"type": ["boolean", "null"]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"type": ["boolean", "null"]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}, "created_at": {"anyOf": [{"additionalProperties": false, "properties": {"$gt": {"format": "date-time", "type": "string"}}, "required": ["$gt"], "type": "object"}, {"additionalProperties": false, "properties": {"$gte": {"format": "date-time", "type": "string"}}, "required": ["$gte"], "type": "object"}, {"format": "date-time", "type": "string"}, {"additionalProperties": false, "properties": {"$ne": {"format": "date-time", "type": "string"}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$lt": {"format": "date-time", "type": "string"}}, "required": ["$lt"], "type": "object"}, {"additionalProperties": false, "properties": {"$lte": {"format": "date-time", "type": "string"}}, "required": ["$lte"], "type": "object"}, {"additionalProperties": false, "properties": {"$between": {"default": [], "items": {"format": "date-time", "type": "string"}, "maxItems": 2, "minItems": 2, "type": "array"}}, "required": ["$between"], "type": "object"}, {"additionalProperties": false, "properties": {"$eq": {"format": "date-time", "type": "string"}}, "required": ["$eq"], "type": "object"}]}, "error_msg": {"anyOf": [{"additionalProperties": false, "properties": {"$startswith": {"minLength": 1, "type": "string"}}, "required": ["$startswith"], "type": "object"}, {"maxLength": 255, "type": ["string", "null"]}, {"additionalProperties": false, "properties": {"$contains": {"minLength": 1, "type": "string"}}, "required": ["$contains"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"maxLength": 255, "type": ["string", "null"]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$iendswith": {"minLength": 1, "type": "string"}}, "required": ["$iendswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$icontains": {"minLength": 1, "type": "string"}}, "required": ["$icontains"], "type": "object"}, {"additionalProperties": false, "properties": {"$endswith": {"minLength": 1, "type": "string"}}, "required": ["$endswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$istartswith": {"minLength": 1, "type": "string"}}, "required": ["$istartswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"maxLength": 255, "type": ["string", "null"]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}, {"additionalProperties": false, "properties": {"$eq": {"maxLength": 255, "type": ["string", "null"]}}, "required": ["$eq"], "type": "object"}]}, "job": {"anyOf": [{"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}, {"additionalProperties": false, "properties": {"$eq": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}, "sample": {"anyOf": [{"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}, {"additionalProperties": false, "properties": {"$eq": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}, "success": {"anyOf": [{"type": ["boolean", "null"]}, {"additionalProperties": false, "properties": {"$eq": {"type": ["boolean", "null"]}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"type": ["boolean", "null"]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"type": ["boolean", "null"]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}}, "type": "object"}}, "type": "object"}, "targetSchema": {"items": {"$ref": "#"}, "type": "array"}}, {"href": "/api/v1/classifications/public", "method": "GET", "rel": "instances_public", "schema": {"additionalProperties": true, "properties": {"page": {"default": 1, "minimum": 1, "type": "integer"}, "per_page": {"default": 20, "maximum": 1000, "minimum": 1, "type": "integer"}, "sort": {"additionalProperties": false, "properties": {"$uri": {"description": "Sort by $uri in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "complete": {"description": "Sort by complete in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "created_at": {"description": "Sort by created_at in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "error_msg": {"description": "Sort by error_msg in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "job": {"description": "Sort by job in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "sample": {"description": "Sort by sample in descending order if 'true', ascending order if 'false'.", "type": "boolean"}, "success": {"description": "Sort by success in descending order if 'true', ascending order if 'false'.", "type": "boolean"}}, "type": "object"}, "where": {"additionalProperties": false, "properties": {"$uri": {"anyOf": [{"pattern": "^\\/api\\/v1\\/classifications\\/[^/]+$", "type": "string"}, {"additionalProperties": false, "properties": {"$eq": {"pattern": "^\\/api\\/v1\\/classifications\\/[^/]+$", "type": "string"}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"pattern": "^\\/api\\/v1\\/classifications\\/[^/]+$", "type": "string"}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"pattern": "^\\/api\\/v1\\/classifications\\/[^/]+$", "type": "string"}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}, "complete": {"anyOf": [{"type": ["boolean", "null"]}, {"additionalProperties": false, "properties": {"$eq": {"type": ["boolean", "null"]}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"type": ["boolean", "null"]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"type": ["boolean", "null"]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}, "created_at": {"anyOf": [{"additionalProperties": false, "properties": {"$gt": {"format": "date-time", "type": "string"}}, "required": ["$gt"], "type": "object"}, {"additionalProperties": false, "properties": {"$gte": {"format": "date-time", "type": "string"}}, "required": ["$gte"], "type": "object"}, {"format": "date-time", "type": "string"}, {"additionalProperties": false, "properties": {"$ne": {"format": "date-time", "type": "string"}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$lt": {"format": "date-time", "type": "string"}}, "required": ["$lt"], "type": "object"}, {"additionalProperties": false, "properties": {"$lte": {"format": "date-time", "type": "string"}}, "required": ["$lte"], "type": "object"}, {"additionalProperties": false, "properties": {"$between": {"default": [], "items": {"format": "date-time", "type": "string"}, "maxItems": 2, "minItems": 2, "type": "array"}}, "required": ["$between"], "type": "object"}, {"additionalProperties": false, "properties": {"$eq": {"format": "date-time", "type": "string"}}, "required": ["$eq"], "type": "object"}]}, "error_msg": {"anyOf": [{"additionalProperties": false, "properties": {"$startswith": {"minLength": 1, "type": "string"}}, "required": ["$startswith"], "type": "object"}, {"maxLength": 255, "type": ["string", "null"]}, {"additionalProperties": false, "properties": {"$contains": {"minLength": 1, "type": "string"}}, "required": ["$contains"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"maxLength": 255, "type": ["string", "null"]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$iendswith": {"minLength": 1, "type": "string"}}, "required": ["$iendswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$icontains": {"minLength": 1, "type": "string"}}, "required": ["$icontains"], "type": "object"}, {"additionalProperties": false, "properties": {"$endswith": {"minLength": 1, "type": "string"}}, "required": ["$endswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$istartswith": {"minLength": 1, "type": "string"}}, "required": ["$istartswith"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"maxLength": 255, "type": ["string", "null"]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}, {"additionalProperties": false, "properties": {"$eq": {"maxLength": 255, "type": ["string", "null"]}}, "required": ["$eq"], "type": "object"}]}, "job": {"anyOf": [{"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}, {"additionalProperties": false, "properties": {"$eq": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}, "sample": {"anyOf": [{"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}, {"additionalProperties": false, "properties": {"$eq": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"anyOf": [{"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}, "type": "object"}, {"maxLength": 16, "type": ["string", "null"]}]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}, "success": {"anyOf": [{"type": ["boolean", "null"]}, {"additionalProperties": false, "properties": {"$eq": {"type": ["boolean", "null"]}}, "required": ["$eq"], "type": "object"}, {"additionalProperties": false, "properties": {"$ne": {"type": ["boolean", "null"]}}, "required": ["$ne"], "type": "object"}, {"additionalProperties": false, "properties": {"$in": {"default": [], "items": {"type": ["boolean", "null"]}, "minItems": 0, "type": "array", "uniqueItems": true}}, "required": ["$in"], "type": "object"}]}}, "type": "object"}}, "type": "object"}, "targetSchema": {"items": {"$ref": "#"}, "type": "array"}}, {"href": "/api/v1/classifications/{id}/readlevel", "method": "GET", "rel": "readlevel", "targetSchema": {"properties": {"url": {"format": "uri", "type": "string"}}, "type": "object"}}, {"href": "/api/v1/classifications/{id}/results", "method": "GET", "rel": "results", "targetSchema": {"additionalProperties": false, "properties": {"host_tax_ids": {"default": [], "items": {"type": "string"}, "type": "array"}, "n_reads": {"minimum": 1, "type": "integer"}, "table": {"default": [], "items": {"additionalProperties": false, "properties": {"abundance": {"maximum": 1.0, "minimum": 0.0, "type": ["number", "null"]}, "name": {"type": "string"}, "parent_tax_id": {"type": "string"}, "rank": {"type": "string"}, "readcount": {"minimum": 1, "type": "integer"}, "readcount_w_children": {"minimum": 1, "type": "integer"}, "tax_id": {"type": "string"}}, "type": "object"}, "type": "array"}}, "type": "object"}}, {"href": "/api/v1/classifications/{id}", "method": "GET", "rel": "self", "targetSchema": {"$ref": "#"}}], "properties": {"$uri": {"pattern": "^\\/api\\/v1\\/classifications\\/[^/]+$", "readOnly": true, "type": "string"}, "complete": {"type": ["boolean", "null"]}, "created_at": {"format": "date-time", "readOnly": true, "type": "string"}, "error_msg": {"maxLength": 255, "type": ["string", "null"]}, "job": {"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/jobs\\/[^/]+$", "type": "string"}}, "type": "object"}, "sample": {"additionalProperties": false, "properties": {"$ref": {"pattern": "^\\/api\\/v1\\/samples\\/[^/]+$", "type": "string"}}, "type": "object"}, "success": {"type": ["boolean", "null"]}}, "type": "object"}

=== onecodex/onecodex/tests/data/api/v1_experimental/functional_profiles/index.json
[{"$uri": "/api/v1_experimental/functional_profiles/eec4ac90d9104d1e", "complete": true, "created_at": "2022-05-25T17:27:30.622286-07:00", "error_msg": "", "job": {"$ref": "/api/v1/jobs/59e7904ea8ed4202"}, "sample": {"$ref": "/api/v1/samples/37e5151e7bcb4f87"}, "success": true}, {"$uri": "/api/v1_experimental/functional_profiles/bde18eb9407d4c2f", "complete": true, "created_at": "2022-05-25T17:27:30.622286-07:00", "error_msg": "", "job": {"$ref": "/api/v1/jobs/59e7904ea8ed4202"}, "sample": {"$ref": "/api/v1/samples/66c1531cb0b244f6"}, "success": true}, {"$uri": "/api/v1_experimental/functional_profiles/31ddae978aff475f", "complete": true, "created_at": "2022-05-25T17:27:30.622286-07:00", "error_msg": "", "job": {"$ref": "/api/v1/jobs/59e7904ea8ed4202"}, "sample": {"$ref": "/api/v1/samples/543c9c046e3e4e09"}, "success": true}]

=== onecodex/onecodex/tests/api_data/functional_profiles.json
[
    {
        "$uri": "/api/v1/functional_profiles/45a573fb7833449b",
        "complete": true,
        "created_at": "2015-09-26T06:16:39.794227-07:00",
        "error_msg": "",
        "job": {
            "$ref": "/api/v1/jobs/c4f763556452402c"
        },
        "sample": {
            "$ref": "/api/v1/samples/002f55a11aae4b8f"
        },
        "success": true
    }
]
